version: '3'

services:  
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    # command: 'true'
    depends_on:
      - mongodb
    #   - redis
    # container_name: api.local

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - node-mongo:/data/db

  # redis:
  #   image: redis:2.8
  #   ports:
  #     - 6380:6379
  #   container_name: iron.redis.blogfoster.local

volumes:
   node-mongo:
    external: true
  # redis:

# networks:  
#   default:
#     external:
#       name: blogfoster
