version: '3'

services:  
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    # command: 'true'
    depends_on:
      - mongodb
      - redis
    # container_name: api.local

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - node-mongo:/data/db

  redis:
    image: 'redis:3.2-alpine'
    # command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  node-mongo:
    external: true
  redis:
    external: true

# networks:  
#   default:
#     external:
#       name: blogfoster
